import type { NonEmpty, Program, Stage } from '../types';

/**
 * Core: pregnancy-safe abdominal work. The shared stage ids and week boundaries
 * come from the pelvic floor program, but the intent is different — this is
 * deep-core-first strength that never asks for a crunch.
 *
 * Two rules shape every session here:
 *   1. Nothing loads the midline harder than it can hold. The regression is
 *      always in the exercise's own `caution`, so she is never left guessing.
 *   2. Supine work thins out as pregnancy goes on and disappears entirely from
 *      `sustain` onward — upright, side-lying and quadruped positions carry the
 *      load instead.
 */
const stages: NonEmpty<Stage> = [
  {
    id: 'foundation',
    programId: 'core',
    colorKey: 'foundation',
    phase: 'pregnancy',
    title: 'Foundation',
    range: 'Weeks 1–13',
    focus:
      'Before anything gets loaded, the deep core has to switch on with your breath. That connection is the whole first trimester — it is what makes everything later actually work, and it is almost invisible from the outside.',
    emphasis: [
      'Find the deep abdominals on the exhale',
      'Learn what a quiet midline feels like',
      'Two short sessions beat one long one',
    ],
    startWeek: 1,
    endWeek: 13,
    sessions: [
      {
        id: 'core-foundation-a',
        title: 'Deep Core Basics',
        steps: [
          { type: 'hold', exerciseId: 'diaphragmatic-breath', durationSec: 60 },
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 5,
            note: 'The draw-in is small. If your back moves, it is too much.',
          },
          { type: 'hold', exerciseId: 'pelvic-tilt', durationSec: 45 },
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
        ],
      },
      {
        id: 'core-foundation-b',
        title: 'Standing Tall',
        steps: [
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
          {
            type: 'reps',
            exerciseId: 'standing-march',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 5,
          },
          { type: 'hold', exerciseId: 'cat-cow', durationSec: 60 },
        ],
      },
    ],
  },
  {
    id: 'build',
    programId: 'core',
    colorKey: 'build',
    phase: 'pregnancy',
    title: 'Build',
    range: 'Weeks 14–27',
    focus:
      'The best window for real core strength. Sickness has usually settled and the bump is not yet in the way, so this is where planks, side work and anti-rotation earn their place. Everything is judged by whether the midline stays flat.',
    emphasis: [
      'Load the trunk from every direction',
      'Watch the midline — doming means regress',
      'Breathe through the holds, never brace against them',
    ],
    startWeek: 14,
    endWeek: 27,
    sessions: [
      {
        id: 'core-build-a',
        title: 'Loaded Core',
        steps: [
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'wall-plank',
            reps: 4,
            liftSec: 2,
            holdSec: 20,
            releaseSec: 3,
            restSec: 20,
            note: 'Step closer to the wall the moment the line starts to sag.',
          },
          {
            type: 'reps',
            exerciseId: 'side-plank-knees',
            reps: 4,
            liftSec: 2,
            holdSec: 15,
            releaseSec: 3,
            restSec: 20,
          },
          {
            type: 'reps',
            exerciseId: 'bird-dog',
            reps: 8,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 5,
          },
        ],
      },
      {
        id: 'core-build-b',
        title: 'All Directions',
        steps: [
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
          {
            type: 'reps',
            exerciseId: 'standing-march',
            reps: 10,
            liftSec: 2,
            holdSec: 3,
            releaseSec: 2,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'anti-rotation-reach',
            reps: 8,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'side-lying-leg-lift',
            reps: 10,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 4,
          },
          { type: 'hold', exerciseId: 'cat-cow', durationSec: 45 },
        ],
      },
      {
        id: 'core-build-c',
        title: 'Control',
        steps: [
          {
            type: 'reps',
            exerciseId: 'dead-bug-heel-tap',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 5,
            note: 'Use the pillow wedge, and keep the range small enough that your back stays put.',
          },
          {
            type: 'reps',
            exerciseId: 'tall-kneel-hold',
            reps: 3,
            liftSec: 2,
            holdSec: 30,
            releaseSec: 3,
            restSec: 20,
          },
          {
            type: 'reps',
            exerciseId: 'side-plank-knees',
            reps: 4,
            liftSec: 2,
            holdSec: 15,
            releaseSec: 3,
            restSec: 20,
          },
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
        ],
      },
    ],
  },
  {
    id: 'sustain',
    programId: 'core',
    colorKey: 'sustain',
    phase: 'pregnancy',
    title: 'Sustain',
    range: 'Weeks 28–34',
    focus:
      'Maintain rather than chase. The bump is doing real work now and the linea alba is under genuine load, so this stage trades range and reps for position — everything moves upright, side-lying or onto hands and knees.',
    emphasis: [
      'Hold what you built, do not push it',
      'Nothing flat on your back',
      'Stop the set at the first sign of doming',
    ],
    startWeek: 28,
    endWeek: 34,
    sessions: [
      {
        id: 'core-sustain-a',
        title: 'Steady',
        steps: [
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'wall-plank',
            reps: 3,
            liftSec: 2,
            holdSec: 20,
            releaseSec: 3,
            restSec: 25,
          },
          {
            type: 'reps',
            exerciseId: 'side-lying-leg-lift',
            reps: 10,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 5,
          },
          { type: 'hold', exerciseId: 'cat-cow', durationSec: 60 },
        ],
      },
      {
        id: 'core-sustain-b',
        title: 'Upright Core',
        steps: [
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
          {
            type: 'reps',
            exerciseId: 'standing-march',
            reps: 10,
            liftSec: 2,
            holdSec: 3,
            releaseSec: 2,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'anti-rotation-reach',
            reps: 8,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'tall-kneel-hold',
            reps: 3,
            liftSec: 2,
            holdSec: 25,
            releaseSec: 3,
            restSec: 20,
          },
        ],
      },
      {
        id: 'core-sustain-c',
        title: 'Side and Back',
        steps: [
          {
            type: 'reps',
            exerciseId: 'side-plank-knees',
            reps: 3,
            liftSec: 2,
            holdSec: 15,
            releaseSec: 3,
            restSec: 25,
          },
          {
            type: 'reps',
            exerciseId: 'side-lying-clam',
            reps: 10,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'bird-dog',
            reps: 8,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 5,
          },
          { type: 'hold', exerciseId: 'rest-and-breathe', durationSec: 60 },
        ],
      },
    ],
  },
  {
    id: 'prepare',
    programId: 'core',
    colorKey: 'prepare',
    phase: 'pregnancy',
    title: 'Prepare',
    range: 'Week 35 onward',
    focus:
      'Core work goes light and practical. The point now is getting in and out of bed, off the sofa and through the day without straining — not adding strength you will not get to keep before the birth.',
    emphasis: [
      'Everyday movements, done well',
      'Short sessions, upright positions',
      'Exhale on the effort, every time',
    ],
    startWeek: 35,
    endWeek: null,
    sessions: [
      {
        id: 'core-prepare-a',
        title: 'Light and Upright',
        steps: [
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
          {
            type: 'reps',
            exerciseId: 'standing-march',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 5,
          },
          { type: 'hold', exerciseId: 'cat-cow', durationSec: 60 },
        ],
      },
      {
        id: 'core-prepare-b',
        title: 'Gentle Support',
        steps: [
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 5,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 6,
          },
          {
            type: 'reps',
            exerciseId: 'side-lying-leg-lift',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'sit-to-stand',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 5,
          },
          { type: 'hold', exerciseId: 'rest-and-breathe', durationSec: 60 },
        ],
      },
      {
        id: 'core-prepare-c',
        title: 'Everyday Carry',
        steps: [
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
          {
            type: 'reps',
            exerciseId: 'sit-to-stand',
            reps: 10,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'anti-rotation-reach',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 6,
          },
          { type: 'hold', exerciseId: 'gentle-walk', durationSec: 300 },
        ],
      },
    ],
  },
  {
    id: 'recover',
    programId: 'core',
    colorKey: 'recover',
    phase: 'postpartum',
    title: 'Recover',
    range: 'First two weeks',
    focus:
      'There is no core training in the first two weeks. Your abdominal wall has just been through something enormous and the only useful thing you can do for it is breathe well and let it be. That is not a consolation prize — it is the actual first step.',
    emphasis: [
      'Breath only, lying down',
      'No holding, no lifting, no testing it',
      'Rest is the exercise',
    ],
    startWeek: 0,
    endWeek: 1,
    sessions: [
      {
        id: 'core-recover-a',
        title: 'Nothing to Do',
        steps: [
          { type: 'hold', exerciseId: 'rest-and-breathe', durationSec: 180 },
          { type: 'hold', exerciseId: 'diaphragmatic-breath', durationSec: 120 },
        ],
      },
      {
        id: 'core-recover-b',
        title: 'First Breaths',
        steps: [
          { type: 'hold', exerciseId: 'diaphragmatic-breath', durationSec: 90 },
          { type: 'hold', exerciseId: 'connection-breath', durationSec: 90 },
          { type: 'hold', exerciseId: 'rest-and-breathe', durationSec: 120 },
        ],
      },
    ],
  },
  {
    id: 'reconnect',
    programId: 'core',
    colorKey: 'reconnect',
    phase: 'postpartum',
    title: 'Reconnect',
    range: 'Weeks 2–5',
    focus:
      'Now the deep core comes back online, in the same order it was built the first time: breath, then a gentle draw-in, then a little movement on top. Any doming or heaviness means you are ahead of yourself.',
    emphasis: [
      'Breath before load, again',
      'Small ranges, quiet midline',
      'Walking counts, and counts a lot',
    ],
    startWeek: 2,
    endWeek: 5,
    sessions: [
      {
        id: 'core-reconnect-a',
        title: 'Switching On',
        steps: [
          { type: 'hold', exerciseId: 'diaphragmatic-breath', durationSec: 60 },
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 6,
          },
          { type: 'hold', exerciseId: 'pelvic-tilt', durationSec: 45 },
          { type: 'hold', exerciseId: 'gentle-walk', durationSec: 300 },
        ],
      },
      {
        id: 'core-reconnect-b',
        title: 'Easy Load',
        steps: [
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 6,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'side-lying-leg-lift',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 5,
          },
          {
            type: 'reps',
            exerciseId: 'heel-slide',
            reps: 8,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 5,
          },
          { type: 'hold', exerciseId: 'posture-reset', durationSec: 45 },
        ],
      },
    ],
  },
  {
    id: 'rebuild',
    programId: 'core',
    colorKey: 'rebuild',
    phase: 'postpartum',
    title: 'Rebuild',
    range: 'Week 6 onward',
    focus:
      'Progressive strength, properly. Planks, side work and loaded holds come back in, and they can keep going for as long as you want them to. This is also the point to get assessed if the midline still separates under load.',
    emphasis: [
      'Add load, keep the midline quiet',
      'Both sides, every session',
      'Get checked if doming persists',
    ],
    startWeek: 6,
    endWeek: null,
    sessions: [
      {
        id: 'core-rebuild-a',
        title: 'Real Load',
        steps: [
          {
            type: 'reps',
            exerciseId: 'quadruped-core-breath',
            reps: 5,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'wall-plank',
            reps: 4,
            liftSec: 2,
            holdSec: 25,
            releaseSec: 3,
            restSec: 20,
          },
          {
            type: 'reps',
            exerciseId: 'side-plank-knees',
            reps: 4,
            liftSec: 2,
            holdSec: 20,
            releaseSec: 3,
            restSec: 20,
          },
          {
            type: 'reps',
            exerciseId: 'bird-dog',
            reps: 10,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 4,
          },
        ],
      },
      {
        id: 'core-rebuild-b',
        title: 'Carry and Lift',
        steps: [
          {
            type: 'reps',
            exerciseId: 'standing-march',
            reps: 10,
            liftSec: 2,
            holdSec: 3,
            releaseSec: 2,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'anti-rotation-reach',
            reps: 10,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 2,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'sit-to-stand',
            reps: 10,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 2,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'bridge',
            reps: 10,
            liftSec: 2,
            holdSec: 4,
            releaseSec: 3,
            restSec: 4,
          },
        ],
      },
      {
        id: 'core-rebuild-c',
        title: 'Full Load',
        steps: [
          {
            type: 'reps',
            exerciseId: 'dead-bug-heel-tap',
            reps: 10,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 4,
          },
          {
            type: 'reps',
            exerciseId: 'wall-plank',
            reps: 4,
            liftSec: 2,
            holdSec: 30,
            releaseSec: 3,
            restSec: 20,
          },
          {
            type: 'reps',
            exerciseId: 'tall-kneel-hold',
            reps: 3,
            liftSec: 2,
            holdSec: 40,
            releaseSec: 3,
            restSec: 20,
          },
          {
            type: 'reps',
            exerciseId: 'side-lying-leg-lift',
            reps: 12,
            liftSec: 2,
            holdSec: 2,
            releaseSec: 3,
            restSec: 4,
          },
        ],
      },
    ],
  },
];

export const coreProgram: Program = {
  id: 'core',
  colorKey: 'core',
  title: 'Core',
  blurb: 'Deep-core strength that keeps the midline quiet. No crunches, ever.',
  stages,
};
